imaging2: imaging::MrepModel< position_t, atom_t, connection_t > Class Template Reference
imaging::MrepModel< position_t, atom_t, connection_t > Class Template Reference
MrepModel
#include <MrepModel.hpp>
Public Member Functions
MrepModel (const position_t &position, size_t n_atoms=0, size_t n_connections=0)
void resize (size_t n_atoms, size_t n_connections)
const atom_t & atom (size_t i) const
void set_atom (size_t i, const atom_t &atom)
size_t n_atoms () const
const connection_t & connection (size_t i) const
void set_connection (size_t i, const connection_t &connection)
size_t n_connections () const
const position_t & position () const
void set_position (const position_t &position)
size_t start_atom (size_t atom_index) const
size_t atom_connection (size_t atom_index) const
void exponential (const ublas::vector< float_t > &vector, ShapeInterface &shape) const
void logarithm (const ShapeInterface &shape, ublas::vector< float_t > &vector) const
size_t dimension () const
Protected Attributes
position_t _position
std::vector< atom_t > _atoms
std::vector< connection_t > _connections
Detailed Description
template<class position_t, class atom_t, class connection_t>
class imaging::MrepModel< position_t, atom_t, connection_t >
MrepModel
Member Function Documentation
template<class position_t, class atom_t, class connection_t> void imaging::MrepModel< position_t, atom_t, connection_t >::exponential (const ublas::vector< float_t > & vector, ShapeInterface & shape) const [inline, virtual]
Computes the Riemannian exponential of vector with respect to *this and stores the result in shape. In other words, shape is the projection of the tangent vector vector in the tangent space at the *this shape on the shape manifold.
Implements imaging::ShapeInterface.
Referenced by imaging::MrepModel< imaging::Position2d, imaging::MrepAtom, imaging::imaging::MrepConnection< 2 > >::exponential().
template<class position_t, class atom_t, class connection_t> void imaging::MrepModel< position_t, atom_t, connection_t >::logarithm (const ShapeInterface & shape, ublas::vector< float_t > & vector) const [inline, virtual]
Computes the Riemannian logarithm of shape with respect to *this and stores the result in vector. In other words, vector is the projection of shape on the tangent space at the *this shape on the shape manifold.
Implements imaging::ShapeInterface.
Referenced by imaging::MrepModel< imaging::Position2d, imaging::MrepAtom, imaging::imaging::MrepConnection< 2 > >::logarithm().
template<class position_t, class atom_t, class connection_t> size_t imaging::MrepModel< position_t, atom_t, connection_t >::dimension () const [inline, virtual]
Returns the parametric dimension of the shape object. This is the same as the dimension of the shape manifold the shape belongs to. It should not be confused with the spatial dimension N.
Implements imaging::ShapeInterface.
Referenced by imaging::MrepModel< imaging::Position2d, imaging::MrepAtom, imaging::imaging::MrepConnection< 2 > >::dimension().
The documentation for this class was generated from the following file:
imaging2/shape/mrep/MrepModel.hpp