imaging2: Polytope Module
Polytope Module
Classes
class imaging::Polygon
Planar polygon with multiple outlines and holes.
class imaging::SimplePolygon
Planar polygon defined by one polygonal boundary curve.
class imaging::imaging::xml_handler< Polygon >
class imaging::imaging::xml_handler< SimplePolygon >
Functions
GraphicsInterface & imaging::operator<< (GraphicsInterface &out, const Polygon &polygon)
GraphicsInterface & imaging::operator<< (GraphicsInterface &out, const SimplePolygon &polygon)
void imaging::polygon_union (const Polygon &poly_1, const Polygon &poly_2, Polygon &result)
float_t imaging::compute_intersection_volume (const SimplePolygon &poly_a, const SimplePolygon &poly_b)
Detailed Description
The polytope module is mainly a utility module which defines classes for simple polygons and multiply connected polygons with holes. It includes functions to compute the union of polygons and the intersection volume of polygons using third-party code (more should be added).
Function Documentation
float_t imaging::compute_intersection_volume (const SimplePolygon & poly_a, const SimplePolygon & poly_b)
#include <polytope/SimplePolygon.hpp>
Computes the volume of the intersection of poly_a and poly_b.
References imaging::SimplePolygon::n_vertices(), and imaging::SimplePolygon::vertex().
GraphicsInterface & imaging::operator<< (GraphicsInterface & out, const SimplePolygon & polygon)
#include <polytope/gio.hpp>
References imaging::GraphicsInterface::polygon(), and imaging::SimplePolygon::vertices().
GraphicsInterface & imaging::operator<< (GraphicsInterface & out, const Polygon & polygon)
#include <polytope/gio.hpp>
References imaging::Polygon::contour(), imaging::Polygon::hole(), imaging::Polygon::n_contours(), and imaging::Polygon::n_holes().
void imaging::polygon_union (const Polygon & poly_1, const Polygon & poly_2, Polygon & result)
#include <polytope/Polygon.hpp>
Computes the union of poly_1 and poly_2 and writes it to result.
Referenced by imaging::PolygonModel2d::compute_boundary().