imaging2: M-Rep Module
M-Rep Module
[Shape Module]
Classes
class imaging::MrepModel2d
Medial axis parametrization of planar shapes.
class imaging::MrepSkeleton2d
Medial axis parametrization of planar shapes.
class imaging::PolygonModel2d
Medial axis parametrization of planar shapes.
class imaging::imaging::xml_handler< Position2d >
class imaging::imaging::xml_handler< MrepAtom >
class imaging::imaging::xml_handler< MrepConnection< 2 > >
class imaging::imaging::xml_handler< MrepModel2d >
class imaging::imaging::xml_handler< PolygonModel2d >
Functions
GraphicsInterface & imaging::operator<< (GraphicsInterface &out, const MrepModel2d &model)
GraphicsInterface & imaging::operator<< (GraphicsInterface &out, const PolygonModel2d &model)
Function Documentation
GraphicsInterface & imaging::operator<< (GraphicsInterface & out, const PolygonModel2d & model)
#include <shape/mrep/gio.hpp>
References imaging::MrepModel< position_t, atom_t, connection_t >::atom(), imaging::MrepSkeleton2d::atom_center(), imaging::MrepSkeleton2d::atom_radius(), imaging::Color::BLUE, imaging::GraphicsInterface::circle(), imaging::PolygonModel2d::compute_boundary(), imaging::Color::CYAN, imaging::GraphicsInterface::get_stream_status(), imaging::MrepModel< position_t, atom_t, connection_t >::n_atoms(), imaging::GraphicsInterface::polyline(), imaging::Color::RED, imaging::GraphicsInterface::vertex(), and imaging::Color::YELLOW.
GraphicsInterface & imaging::operator<< (GraphicsInterface & out, const MrepModel2d & model)
#include <shape/mrep/gio.hpp>
References imaging::MrepModel< position_t, atom_t, connection_t >::atom(), imaging::MrepSkeleton2d::atom_center(), imaging::MrepSkeleton2d::atom_radius(), imaging::Color::BLUE, imaging::GraphicsInterface::circle(), imaging::MrepModel2d::compute_boundary(), imaging::Color::CYAN, imaging::GraphicsInterface::get_stream_status(), imaging::MrepModel< position_t, atom_t, connection_t >::n_atoms(), imaging::GraphicsInterface::polyline(), imaging::Color::RED, imaging::GraphicsInterface::vertex(), and imaging::Color::YELLOW.