imaging2: Statistic Module
Statistic Module
Classes
class imaging::LinearPca
Linear principal component analysis.
Functions
void imaging::mean (const ublas::matrix< float_t > &data, ublas::vector< float_t > &result)
void imaging::var (const ublas::matrix< float_t > &data, ublas::vector< float_t > &result)
float_t imaging::mean (const ublas::vector< float_t > &data)
float_t imaging::var (const ublas::vector< float_t > &data)
Detailed Description
The statistics module is a utility module which contains utility functions to compute means and variances. Additionally it includes an implementation of the linear principal component analysis (PCA).
Function Documentation
float_t imaging::mean (const ublas::vector< float_t > & data)
#include <statistic/utilities.hpp>
Returns the mean of data.
void imaging::mean (const ublas::matrix< float_t > & data, ublas::vector< float_t > & result)
#include <statistic/utilities.hpp>
Computes the mean of each column of data and writes it to result. The vector result is resized to the number of columns of data upon return.
Referenced by imaging::var().
float_t imaging::var (const ublas::vector< float_t > & data)
#include <statistic/utilities.hpp>
Returns the variance data.
References imaging::mean(), and imaging::square().
void imaging::var (const ublas::matrix< float_t > & data, ublas::vector< float_t > & result)
#include <statistic/utilities.hpp>
Computes the variances of the columns of data and writes them to result. The vector result is resized to the number of columns of data upon return.
References imaging::mean(), and imaging::square().