imaging2: Shape Module
Shape Module
Modules
M-Rep Module
Classes
class imaging::BoundaryDiscretizer< N >
Abstract class interface for discretizations of shape boundaries.
class imaging::Box< N >
N-dimensional box (hyperrectangle).
class imaging::BsplineShape
Class for shapes determined by boundary spline curves in the plane.
class imaging::Circle
Class for circles in the plane.
class imaging::DiscretizableShapeInterface< N >
Abstract class interface for discretizable shapes of dimension N.
class imaging::ShapeEnergyInterface< shape_t >
Abstract class interface for energies depending on vector valued input data which define an input shape.
class imaging::ShapeInterface
Abstract class interface for shapes on a shape parameter manifold.
class imaging::ShapeStatistics< shape_t >
Computes the mean shape and the covariance of a shape distribution and samples from this distribution.
class imaging::imaging::xml_handler< Circle >
Functions
template<std::size_t N>
void imaging::compute_intersection_box (const Box< N > &box_a, const Box< N > &box_b, Box< N > &result)
template<std::size_t N>
bool imaging::do_intersect (const Box< N > &box_a, const Box< N > &box_b)
template<std::size_t N>
float_t imaging::compute_intersection_volume (const Box< N > &box_a, const Box< N > &box_b)
GraphicsInterface & imaging::operator<< (GraphicsInterface &out, const Circle &circle)
GraphicsInterface & imaging::operator<< (GraphicsInterface &out, const BsplineShape &spline_shape)
Detailed Description
The shape module defines a common interface for finite dimensional shape manifolds of arbitrary spatial dimension. In addition functions to integrate shapes, i.e. integration of (vector-valued) functions along the shape boundary, are provided. Implemented shapes are circles, B-spline curves and two kinds of M-Reps.
Function Documentation
template<std::size_t N> void imaging::compute_intersection_box (const Box< N > & box_a, const Box< N > & box_b, Box< N > & result) [inline]
#include <shape/Box.hpp>
Computes the intersection of two N-dimensional boxes and writes it to result.
References imaging::Box< N >::_lower_corner, imaging::Box< N >::_upper_corner, imaging::max(), and imaging::min().
Referenced by imaging::compute_intersection_volume(), and imaging::do_intersect().
template<std::size_t N> float_t imaging::compute_intersection_volume (const Box< N > & box_a, const Box< N > & box_b) [inline]
#include <shape/Box.hpp>
Computes the volume of the intersection of two N-dimensional boxes.
References imaging::compute_intersection_box(), imaging::Box< N >::compute_volume(), and imaging::do_intersect().
template<std::size_t N> bool imaging::do_intersect (const Box< N > & box_a, const Box< N > & box_b) [inline]
#include <shape/Box.hpp>
Determines if two N-dimensional boxes intersect.
References imaging::compute_intersection_box(), and imaging::Box< N >::is_empty().
Referenced by imaging::compute_intersection_volume().
GraphicsInterface & imaging::operator<< (GraphicsInterface & out, const BsplineShape & spline_shape)
#include <shape/gio.hpp>
References imaging::BsplineShape::curve().
GraphicsInterface & imaging::operator<< (GraphicsInterface & out, const Circle & circle)
#include <shape/gio.hpp>
References imaging::Circle::center(), imaging::GraphicsInterface::circle(), and imaging::Circle::radius().