imaging2: Core Module
Core Module
Namespaces
namespace imaging
Main library namespace (abbreviated as img).
Classes
class imaging::Cmessage
Implementation of MessageInterface.
class imaging::DifferentiableFunctionalInterface
Abstract class interface of differentiable functionals depending on vector valued input data.
class imaging::Exception
Generic exception with custom error message.
class imaging::MathException
Mathematical exception.
class imaging::FileIoException
File I/O exception.
class imaging::FunctionalInterface
Abstract class interface for functionals depending on vector valued input data.
class imaging::FunctionInterface< A, V >
Abstract class template for functions.
class imaging::MessageInterface
Abstract class interface for displaying log messages.
class boost::numeric::ublas::fixed_matrix< T, M, N, L >
uBLAS compatible class template for matrices of fixed size.
class boost::numeric::ublas::fixed_vector< T, N >
uBLAS compatible class template for vectors of fixed size.
class imaging::imaging::xml_handler< ublas::matrix< float_t > >
class imaging::imaging::xml_handler< ublas::vector< float_t > >
Typedefs
typedef double imaging::float_t
typedef std::size_t imaging::size_t
typedef std::complex< float_t > imaging::complex_t
Functions
template<class element_t>
std::ostream & imaging::operator<< (std::ostream &out, const std::vector< element_t > &vector)
template<class key_t, class data_t>
std::ostream & imaging::operator<< (std::ostream &out, const std::map< key_t, data_t > &map)
template<class data_t>
std::ostream & imaging::operator<< (std::ostream &out, const std::set< data_t > &set)
template<class key_t, class data_t>
std::ostream & imaging::operator<< (std::ostream &out, const std::pair< key_t, data_t > &pair)
void imaging::output_matrix_matlab_style (std::ostream &out, const ublas::matrix< float_t > &matrix)
void imaging::output_vector_matlab_style (std::ostream &out, const ublas::vector< float_t > &vector)
void imaging::output_matrix_gnuplot_style (std::ostream &out, const ublas::matrix< float_t > &matrix)
void imaging::output_vector_gnuplut_style (std::ostream &out, const ublas::vector< float_t > &vector)
float_t imaging::uniform_distribution ()
float_t imaging::symmetric_uniform_distribution ()
float_t imaging::normal_distribution ()
GraphicsInterface & imaging::operator<< (GraphicsInterface &out, const ublas::fixed_vector< float_t, 2 > &vertex)
float_t imaging::determinant (const ublas::fixed_matrix< float_t, 2, 2 > &A)
ublas::fixed_matrix< float_t, 2, 2 > imaging::inverse (const ublas::fixed_matrix< float_t, 2, 2 > &A)
float_t imaging::determinant (const ublas::fixed_matrix< float_t, 3, 3 > &A)
ublas::fixed_matrix< float_t, 3, 3 > imaging::inverse (const ublas::fixed_matrix< float_t, 3, 3 > &A)
ublas::fixed_matrix< float_t, 1, 1 > imaging::inverse (const ublas::fixed_matrix< float_t, 1, 1 > &A)
ublas::fixed_matrix< float_t, 2, 2 > imaging::rotation_matrix (float_t alpha)
template<class num_t>
num_t imaging::max (const num_t a, const num_t b)
template<class num_t>
num_t imaging::min (const num_t a, const num_t b)
template<class num_t>
num_t imaging::square (num_t a)
template<class num_t>
num_t imaging::power (num_t a, size_t b)
template<class num_t>
num_t imaging::abs (num_t a)
template<class num_t>
num_t imaging::sign (num_t a)
float_t imaging::delta (size_t base, size_t t)
float_t imaging::clockwise_difference (float_t angle_1, float_t angle_2)
float_t imaging::counter_clockwise_difference (float_t angle_1, float_t angle_2)
const ublas::fixed_vector
< float_t, 2 > imaging::polar2cartesian (float_t radius, float_t angle)
float_t imaging::radius (const ublas::fixed_vector< float_t, 2 > &v)
float_t imaging::angle (const ublas::fixed_vector< float_t, 2 > &v)
Variables
const double imaging::PI = 3.1415926
const double imaging::SQUARE_ROOT_2 = 1.414213562373095049
const double imaging::SQUARE_ROOT_3 = 1.73205080757
Detailed Description
The core module defines the namespace imaging (img) and the types img::float_t and img::size_t. Furthermore it includes uBLAS and its imaging2 specific extensions. It also provides a standard interface to display log messages, MessageInterface. Several mathematical utility functions are also defined in core.
Typedef Documentation
typedef std::complex<float_t> imaging::complex_t
#include <core/float_types.hpp>
Defines imaging::complex_t to be std::complex<float_t>.
typedef double imaging::float_t
#include <core/float_types.hpp>
Defines imaging::float_t to be double.
typedef std::size_t imaging::size_t
#include <core/float_types.hpp>
Defines imaging::size_t to be std::size_t.
Function Documentation
template<class num_t> num_t imaging::abs (num_t a) [inline]
#include <core/utilities.hpp>
Returns the absolute value of a.
float_t imaging::angle (const ublas::fixed_vector< float_t, 2 > & v)
#include <core/vector_utilities.hpp>
Returns the polar angle of v.
References imaging::PI, and imaging::radius().
Referenced by imaging::MrepModel2d::compute_boundary().
float_t imaging::clockwise_difference (float_t angle_1, float_t angle_2)
#include <core/utilities.hpp>
Returns the clockwise difference from angle_1 to angle_2 in the interval [0, 2 Pi].
References imaging::PI.
Referenced by imaging::MrepModel2d::compute_boundary(), and imaging::counter_clockwise_difference().
float_t imaging::counter_clockwise_difference (float_t angle_1, float_t angle_2)
#include <core/utilities.hpp>
Returns the counterclockwise difference from angle_1 to angle_2 in the interval [0, 2 Pi].
References imaging::clockwise_difference().
Referenced by imaging::MrepModel2d::compute_boundary().
float_t imaging::delta (size_t base, size_t t)
#include <core/utilities.hpp>
Returns 1.0 if base equals t and 0.0 otherwise.
float_t imaging::determinant (const ublas::fixed_matrix< float_t, 3, 3 > & A)
#include <core/matrix_utilities.hpp>
Returns the determinant of A.
float_t imaging::determinant (const ublas::fixed_matrix< float_t, 2, 2 > & A)
#include <core/matrix_utilities.hpp>
Returns the determinant of A.
Referenced by imaging::inverse().
ublas::fixed_matrix< float_t, 1, 1 > imaging::inverse (const ublas::fixed_matrix< float_t, 1, 1 > & A)
#include <core/matrix_utilities.hpp>
Returns the inverse of A.
ublas::fixed_matrix< float_t, 3, 3 > imaging::inverse (const ublas::fixed_matrix< float_t, 3, 3 > & A)
#include <core/matrix_utilities.hpp>
Returns the inverse of A.
References imaging::determinant().
ublas::fixed_matrix< float_t, 2, 2 > imaging::inverse (const ublas::fixed_matrix< float_t, 2, 2 > & A)
#include <core/matrix_utilities.hpp>
Returns the inverse of A.
References imaging::determinant().
Referenced by imaging::FemKernel< fem_types >::set_boundary_element(), and imaging::FemKernel< fem_types >::set_element().
template<class num_t> num_t imaging::max (const num_t a, const num_t b) [inline]
#include <core/utilities.hpp>
Returns max(a, b).
Referenced by imaging::compute_intersection_box(), imaging::eigensystem(), imaging::ellipse_grid(), imaging::PeriodicBspline< boost::numeric::ublas::fixed_vector< double, 2 > >::is_in_basis_spline_support(), imaging::maximum(), and imaging::Cmessage::operator()().
template<class num_t> num_t imaging::min (const num_t a, const num_t b) [inline]
#include <core/utilities.hpp>
Returns min(a, b).
Referenced by imaging::compute_intersection_box(), and imaging::minimum().
float_t imaging::normal_distribution ()
#include <core/distribution_utilities.hpp>
Returns a sample from the N(0, 1)-normal distribution.
Referenced by imaging::CovarianceMatrixAdaptation::minimize(), and imaging::ShapeStatistics< shape_t >::random_shape_sample().
GraphicsInterface& imaging::operator<< (GraphicsInterface & out, const ublas::fixed_vector< float_t, 2 > & vertex)
#include <core/gio.hpp>
template<class key_t, class data_t> std::ostream& imaging::operator<< (std::ostream & out, const std::pair< key_t, data_t > & pair) [inline]
#include <core/cio.hpp>
template<class data_t> std::ostream& imaging::operator<< (std::ostream & out, const std::set< data_t > & set) [inline]
#include <core/cio.hpp>
template<class key_t, class data_t> std::ostream& imaging::operator<< (std::ostream & out, const std::map< key_t, data_t > & map) [inline]
#include <core/cio.hpp>
template<class element_t> std::ostream& imaging::operator<< (std::ostream & out, const std::vector< element_t > & vector) [inline]
#include <core/cio.hpp>
void imaging::output_matrix_gnuplot_style (std::ostream & out, const ublas::matrix< float_t > & matrix)
#include <core/cio.hpp>
void imaging::output_matrix_matlab_style (std::ostream & out, const ublas::matrix< float_t > & matrix)
#include <core/cio.hpp>
void imaging::output_vector_gnuplut_style (std::ostream & out, const ublas::vector< float_t > & vector)
#include <core/cio.hpp>
void imaging::output_vector_matlab_style (std::ostream & out, const ublas::vector< float_t > & vector)
#include <core/cio.hpp>
const ublas::fixed_vector< float_t, 2 > imaging::polar2cartesian (float_t radius, float_t angle)
#include <core/vector_utilities.hpp>
Converts the polar coordinates (radius, angle) to cartesian coordinates and returns the result. Mathematically:
Referenced by imaging::MrepModel2d::compute_boundary().
template<class num_t> num_t imaging::power (num_t a, size_t b) [inline]
#include <core/utilities.hpp>
Returns ab, where b is a non-negative integer.
float_t imaging::radius (const ublas::fixed_vector< float_t, 2 > & v)
#include <core/vector_utilities.hpp>
Returns the length of v.
Referenced by imaging::angle().
ublas::fixed_matrix< float_t, 2, 2 > imaging::rotation_matrix (float_t alpha)
#include <core/matrix_utilities.hpp>
For the angle alpha, this function returns the rotation matrix
Referenced by imaging::GraphicsInterface::arrow(), and imaging::MrepSkeleton2d::atom_center().
template<class num_t> num_t imaging::sign (num_t a) [inline]
#include <core/utilities.hpp>
Returns the sign of a.
template<class num_t> num_t imaging::square (num_t a) [inline]
#include <core/utilities.hpp>
Returns a2.
Referenced by imaging::GeodesicActiveContourStep< fem_types >::force_vector(), imaging::MumfordShahEnergy< shape_t >::MumfordShahEnergy(), imaging::MumfordShahEnergy< shape_t >::set_argument_with_gradient(), imaging::ShapeStatistics< shape_t >::shape_vector(), imaging::TvFlowStep< fem_types >::stiffness_matrix(), imaging::GeodesicActiveContourStep< fem_types >::stiffness_matrix(), and imaging::var().
float_t imaging::symmetric_uniform_distribution ()
#include <core/distribution_utilities.hpp>
Returns a sample from the uniform distribution on the interval [-1, 1].
Referenced by imaging::ShapeStatistics< shape_t >::random_shape_sample().
float_t imaging::uniform_distribution ()
#include <core/distribution_utilities.hpp>
Returns a sample from the uniform distribution on the interval [0, 1].
Variable Documentation
const double imaging::PI = 3.1415926
#include <core/utilities.hpp>
Defines Pi.
Referenced by imaging::angle(), imaging::GraphicsInterface::arrow(), imaging::clockwise_difference(), imaging::MrepModel2d::compute_boundary(), and imaging::ellipse_grid().
const double imaging::SQUARE_ROOT_2 = 1.414213562373095049
#include <core/utilities.hpp>
Defines the square root of 2.
Referenced by imaging::CovarianceMatrixAdaptation::minimize().
const double imaging::SQUARE_ROOT_3 = 1.73205080757
#include <core/utilities.hpp>
Defines the square root of 2.