imaging2: imaging Namespace Reference
imaging Namespace Reference
[Core Module]
Main library namespace (abbreviated as img).
Classes
class Cmessage
Implementation of MessageInterface.
class DifferentiableFunctionalInterface
Abstract class interface of differentiable functionals depending on vector valued input data.
class Exception
Generic exception with custom error message.
class MathException
Mathematical exception.
class FileIoException
File I/O exception.
class FunctionalInterface
Abstract class interface for functionals depending on vector valued input data.
class FunctionInterface
Abstract class template for functions.
class MessageInterface
Abstract class interface for displaying log messages.
class imaging::xml_handler< ublas::matrix< float_t > >
class imaging::xml_handler< ublas::vector< float_t > >
class Assembler
Assembles the stiffness matrix and force vector of a FE problem.
class ElementIntegrator
Abstract base class of all integrator classes.
class SquareIntegrator
Gaussian integrator on the square.
class CubeIntegrator
Gaussian integrator on the square.
class TriangleIntegrator
Gaussian integrator on the triangle.
class TetrahedraIntegrator
Gaussian integrator on the tetrahedron.
class IntervalIntegrator
Gaussian integrator on the symmetric unit interval.
class PointIntegrator
(Gaussian) integrator on a point.
class DiffusionStep
Implements an implicit time step of an isotropic diffusion equation.
class EquationInterface
Abstract base class of all PDEs to be solved using the finite element module.
class GeodesicActiveContourStep
Implements an implicit time step of the geodesic active contour evolution.
class McmStep
Implements an implicit time step of a mean curvature motion equation.
class PoissonEquation
Implements the Poisson equation with Dirichlet boundary conditions.
class SimpleEquationAdaptor
Converts a SimpleEquationInterface object into an EquationInterface object.
class SimpleEquationInterface
Abstract base class of scalar, elliptic PDEs in divergence form.
class TvFlowStep
Implements an implicit time step of a total variation flow equation.
class FeFunctionInterface
Abstract base class of FE approximations of functions.
class fem_1d_types
FE types for a 1-dimensional FE problem.
class fem_2d_square_types
FE types for a 2-dimensional FE problem with rectangular elements.
class fem_2d_triangle_types
FE types for a 2-dimensional FE problem with triangular elements.
class fem_3d_cube_types
FE types for a 3-dimensional FE problem with cube elements.
class fem_3d_tetrahedra_types
FE types for a 3-dimensional FE problem with tetrahedral elements.
class FemKernel
Computes the values of the shape functions and the element transformation in the integration nodes.
class Grid
Provides the data structure and accessor functions for a FE grid.
class Image2Grid
Constructs FE grids from multi-dimensional images and provides conversion functions between grid and image.
class ShapeFunction
Abstract base class of all shape functions classes.
class Bilinear2dShapeFunction
Bilinear shape function on the square.
class Trilinear3dShapeFunction
class Linear2dShapeFunction
Linear shape function on the triangle.
class Linear3dShapeFunction
Linear shape function on the tetrahedra.
class Linear1dShapeFunction
Linear shape function on the symmetric unit interval.
class SimpleAssembler
Assembles the stiffness matrix and force vector of a FE problem implementing SimpleEquationInterface.
class Transform
Abstract base class of all transformations of the reference element to an element of the FE grid.
class Square2dTransform
Transformation of the square reference element.
class Triangle2dTransform
Transformation of the triangle reference element.
class Tetrahedra3dTransform
Transformation of the tetrahedra reference element.
class Cube3dTransform
Transformation of the symmetric unit interval reference element.
class Interval1dTransform
Transformation of the symmetric unit cube reference element. TODO:.
class DummyGraphics
Graphics output that ignores any input.
class GraphicsInterface
Abstract class interface for graphics output.
class OpenGlViewer
Graphics output that renders graphics using GLUT.
class CastAccessor
Provides casted pixel data type access to images.
class Color
Class for 24-bit color values.
class GrayValue
Class for 8-bit grayscale values.
class Image
Stores image data of arbitrary dimension and pixel type.
class ImageAccessorInterface
Abstract base class of all image accessor classes.
class ImageInterface
Abstract base class of all classes modelling image data.
class InterpolationAdaptorInterface
Abstract base class of image interpolation function which provide pixel values in floating point coordinates.
class PolynomialInterpolationAdaptor
Polynomial interpolation of image values at floating point coordinates.
class ScalarImage
Image with constant pixel values.
class ScalingAccessor
Provides access to rescaled floating point images.
class VectorComponentAccessor
Provides access to different channels of vector valued image data.
class CovarianceMatrixAdaptation
Minimizes energies using covariance matrix adaptation (CMA).
class DifferentiableEnergyInterface
Abstract class interface for differentiable energies depending on vector valued input data.
class DifferentiableFunctionalAdaptor
Converts a DifferentiableFunctionalInterface object into a DifferentiableEnergyInterface object.
class EnergyInterface
Abstract class interface for energies depending on vector valued input data.
class FunctionalAdaptor
Converts a FunctionalInterface object into an EnergyInterface object.
class Lbfgs
Minimizes differentiable energies using the Limited Memory BFGS method (a Quasi-Newton method).
class MinimizerInterface
Abstract base class of iterative minimization methods.
class NlCg
Minimizes differentiable energies using nonlinear conjugated gradients.
class SteepestDescent
Minimizes differentiable energies using steepest descent.
class Polygon
Planar polygon with multiple outlines and holes.
class SimplePolygon
Planar polygon defined by one polygonal boundary curve.
class imaging::xml_handler< Polygon >
class imaging::xml_handler< SimplePolygon >
class MumfordShahEnergy
Simplified Mumford-Shah energy for arbitrary shape classes.
class SnakesEnergy
Snakes energy for arbitrary shape classes.
class StatisticalRegularization
Statistical regularization functional based on an arbitrary shape segmentation functional.
class BoundaryDiscretizer
Abstract class interface for discretizations of shape boundaries.
class Box
N-dimensional box (hyperrectangle).
class BsplineShape
Class for shapes determined by boundary spline curves in the plane.
class Circle
Class for circles in the plane.
class DiscretizableShapeInterface
Abstract class interface for discretizable shapes of dimension N.
class MrepAtom
MrepAtom
class MrepConnection
MrepConnection
class imaging::MrepConnection< 2 >
MrepConnection
class MrepModel
MrepModel
class MrepModel2d
Medial axis parametrization of planar shapes.
class MrepSkeleton2d
Medial axis parametrization of planar shapes.
class PolygonModel2d
Medial axis parametrization of planar shapes.
class Position2d
Stores the coordinates and the rotation of shapes in the plane.
class imaging::xml_handler< Position2d >
class imaging::xml_handler< MrepAtom >
class imaging::xml_handler< MrepConnection< 2 > >
class imaging::xml_handler< MrepModel2d >
class imaging::xml_handler< PolygonModel2d >
class ShapeEnergyInterface
Abstract class interface for energies depending on vector valued input data which define an input shape.
class ShapeInterface
Abstract class interface for shapes on a shape parameter manifold.
class ShapeStatistics
Computes the mean shape and the covariance of a shape distribution and samples from this distribution.
class imaging::xml_handler< Circle >
class BiCgStabSolver
Wrapper class for the BiCGStab solver provided by SPOOLES.
class CgSolver
Wrapper class for the CG solver of provided by ITPACK.
class LuSolver
Wrapper class for the LU solver provided by SPOOLES.
class SolverInterface
Abstract class interface for solver for sparse systems of linear equations.
class Bspline
Class template for B-Splines of arbitrary data type.
class PeriodicBspline
Class template for periodic B-Splines of arbitrary data type.
class imaging::xml_handler< PeriodicBspline< DATA_t > >
class imaging::xml_handler< Bspline< DATA_t > >
class LinearPca
Linear principal component analysis.
class imaging::xml_handler< Person >
class XmlReader
Reads XML files using a stream interface.
class XmlWriter
Reads XML files using a stream interface.
Typedefs
typedef double float_t
typedef std::size_t size_t
typedef std::complex< float_t > complex_t
typedef Image< 2, Color > ColorImage2d
2-dimensional color image.
typedef Image< 2, GrayValue > GrayImage2d
2-dimensional grayscale image.
typedef Image< 3, GrayValue > GrayImage3d
3-dimensional grayscale image.
Functions
void output_matrix_matlab_style (std::ostream &out, const ublas::matrix< float_t > &matrix)
void output_vector_matlab_style (std::ostream &out, const ublas::vector< float_t > &vector)
void output_matrix_gnuplot_style (std::ostream &out, const ublas::matrix< float_t > &matrix)
void output_vector_gnuplut_style (std::ostream &out, const ublas::vector< float_t > &vector)
template<class element_t>
std::ostream & operator<< (std::ostream &out, const std::vector< element_t > &vector)
template<class key_t, class data_t>
std::ostream & operator<< (std::ostream &out, const std::map< key_t, data_t > &map)
template<class data_t>
std::ostream & operator<< (std::ostream &out, const std::set< data_t > &set)
template<class key_t, class data_t>
std::ostream & operator<< (std::ostream &out, const std::pair< key_t, data_t > &pair)
float_t uniform_distribution ()
float_t symmetric_uniform_distribution ()
float_t normal_distribution ()
GraphicsInterface & operator<< (GraphicsInterface &out, const ublas::fixed_vector< float_t, 2 > &vertex)
float_t determinant (const ublas::fixed_matrix< float_t, 2, 2 > &A)
float_t determinant (const ublas::fixed_matrix< float_t, 3, 3 > &A)
ublas::fixed_matrix< float_t, 2, 2 > inverse (const ublas::fixed_matrix< float_t, 2, 2 > &A)
ublas::fixed_matrix< float_t, 3, 3 > inverse (const ublas::fixed_matrix< float_t, 3, 3 > &A)
ublas::fixed_matrix< float_t, 1, 1 > inverse (const ublas::fixed_matrix< float_t, 1, 1 > &A)
ublas::fixed_matrix< float_t, 2, 2 > rotation_matrix (float_t alpha)
float_t clockwise_difference (float_t angle_1, float_t angle_2)
float_t counter_clockwise_difference (float_t angle_1, float_t angle_2)
float_t delta (size_t base, size_t t)
template<class num_t>
num_t max (const num_t a, const num_t b)
template<class num_t>
num_t min (const num_t a, const num_t b)
template<class num_t>
num_t square (num_t a)
template<class num_t>
num_t power (num_t a, size_t b)
template<class num_t>
num_t abs (num_t a)
template<>
float abs (float a)
template<>
double abs (double a)
template<class num_t>
num_t sign (num_t a)
const ublas::fixed_vector
< float_t, 2 > polar2cartesian (float_t radius, float_t angle)
float_t radius (const ublas::fixed_vector< float_t, 2 > &v)
float_t angle (const ublas::fixed_vector< float_t, 2 > &v)
template<size_t N_VERTICES, size_t N_NODES>
std::ostream & operator<< (std::ostream &out, const Element< N_VERTICES, N_NODES > &element)
std::ostream & operator<< (std::ostream &out, const BoundaryElement &element)
template<class fem_types>
std::ostream & operator<< (std::ostream &out, const Grid< fem_types > &grid)
template<class fem_types, class function_t>
function_t::value_t integrate (const function_t &function, const Grid< fem_types > &grid)
template<class fem_types, class function_t>
function_t::value_t maximum (const function_t &function, const Grid< fem_types > &grid)
template<class fem_types, class function_t>
function_t::value_t minimum (const function_t &function, const Grid< fem_types > &grid)
template<class fem_types, class function_t>
function_t::value_t average (const function_t &function, const Grid< fem_types > &grid)
template<>
float_t transform_det (const ublas::fixed_matrix< float_t, 1, 0 > &derivative)
template<>
float_t transform_det (const ublas::fixed_matrix< float_t, 1, 1 > &derivative)
template<>
float_t transform_det (const ublas::fixed_matrix< float_t, 2, 1 > &derivative)
template<>
float_t transform_det (const ublas::fixed_matrix< float_t, 3, 2 > &A)
template<std::size_t M, std::size_t N>
float_t transform_det (const ublas::fixed_matrix< float_t, M, N > &derivative)
template<class fem_types>
GraphicsInterface & operator<< (GraphicsInterface &out, const Grid< fem_types > &grid)
void uniform_grid (float_t lower_bound, float_t upper_bound, std::size_t n_elements, Grid< fem_1d_types > &grid, ublas::compressed_matrix< float_t > &stiffness_matrix_prototype, std::size_t system_size)
void circle_grid (float_t radius, std::size_t n_rings, Grid< fem_2d_triangle_types > &grid, ublas::compressed_matrix< float_t > &stiffness_matrix_prototype, std::size_t system_size)
void ellipse_grid (float_t a, float_t b, std::size_t n_rings, Grid< fem_2d_triangle_types > &grid, ublas::compressed_matrix< float_t > &stiffness_matrix_prototype, std::size_t system_size)
void triangulate_shape (const BoundaryDiscretizer< 2 > &shape_discretizer, float_t max_triangle_area, Grid< fem_2d_triangle_types > &grid, ublas::compressed_matrix< float_t > &stiffness_matrix_prototype, std::size_t system_size)
std::ostream & operator<< (std::ostream &out, const GrayValue value)
std::ostream & operator<< (std::ostream &out, const Color &value)
std::istream & operator>> (std::istream &in, GrayValue &value)
std::istream & operator>> (std::istream &in, Color &value)
template<size_t N, class DATA_t>
std::ostream & operator<< (std::ostream &out, const ImageInterface< N, DATA_t > &image)
GraphicsInterface & operator<< (GraphicsInterface &out, const ColorImage2d &image)
template<std::size_t N, class DATA_t>
GraphicsInterface & operator<< (GraphicsInterface &out, const Image< N, DATA_t > &image)
template<size_t N>
bool increment_index (const ublas::fixed_vector< size_t, N > &dimensions, size_t fixed_component, ublas::fixed_vector< size_t, N > &index)
template<size_t N>
bool increment_index (const ublas::fixed_vector< size_t, N > &dimensions, ublas::fixed_vector< size_t, N > &index)
template<class source_accessor_t, class target_accessor_t>
void copy_image (const source_accessor_t &source, target_accessor_t &target)
template<>
void edge (Image< 2, float_t > &image, float_t radius)
template<>
void blur (Image< 2, float_t > &image, float_t width, float_t sigma)
template<>
void absolute_gradient (Image< 2, float_t > &image)
void draw_level_set (const Image< 2, float_t > &level_set_function, const float_t &level, const Color &color, ColorImage2d &image)
void image2matrix (const Image< 2, float_t > &image, ublas::matrix< float_t > &matrix)
template<class float_accessor_t, class vector_accessor_t>
void compute_divergence_field (const float_accessor_t &image, vector_accessor_t &out)
template<class image_t>
void blur (image_t &image, float_t width, float_t sigma)
template<class image_t>
void edge (image_t &image, float_t radius)
template<class image_t>
void absolute_gradient (image_t &image)
template<class image_t>
image_t::data_t max (const image_t &image)
template<class image_t>
image_t::data_t min (const image_t &image)
template<class image_t>
bool is_pixel (const image_t &image, const ublas::fixed_vector< size_t, image_t::dimension > &index)
void eigensystem (const ublas::matrix< float_t > &in, ublas::matrix< float_t > &eigenvectors, ublas::vector< float_t > &eigenvalues)
void symmetric_square_root (const ublas::matrix< float_t > &in, ublas::matrix< float_t > &root)
void square_root (const ublas::matrix< float_t > &in, ublas::matrix< float_t > &root)
void inverse_square_root (const ublas::matrix< float_t > &in, ublas::matrix< float_t > &root)
void inverse (const ublas::matrix< float_t > &in, ublas::matrix< float_t > &out)
GraphicsInterface & operator<< (GraphicsInterface &out, const Polygon &polygon)
GraphicsInterface & operator<< (GraphicsInterface &out, const SimplePolygon &polygon)
void polygon_union (const Polygon &poly_1, const Polygon &poly_2, Polygon &result)
float_t compute_intersection_volume (const SimplePolygon &poly_a, const SimplePolygon &poly_b)
float_t compute_intersection_volume (const BoundaryDiscretizer< 2 > &shape_a, const BoundaryDiscretizer< 2 > &shape_b)
template<std::size_t N>
void compute_intersection_box (const Box< N > &box_a, const Box< N > &box_b, Box< N > &result)
template<std::size_t N>
bool do_intersect (const Box< N > &box_a, const Box< N > &box_b)
template<std::size_t N>
float_t compute_intersection_volume (const Box< N > &box_a, const Box< N > &box_b)
GraphicsInterface & operator<< (GraphicsInterface &out, const Circle &circle)
GraphicsInterface & operator<< (GraphicsInterface &out, const BsplineShape &spline_shape)
GraphicsInterface & operator<< (GraphicsInterface &out, const MrepModel2d &model)
GraphicsInterface & operator<< (GraphicsInterface &out, const PolygonModel2d &model)
void discretize_sector (ublas::fixed_vector< float_t, 2 > center, float_t radius, float_t angle_1, float_t ccw_offset, size_t n_vertices, std::vector< ublas::fixed_vector< float_t, 2 > > vertices)
GraphicsInterface & operator<< (GraphicsInterface &out, const Bspline< ublas::fixed_vector< float_t, 2 > > &curve)
GraphicsInterface & operator<< (GraphicsInterface &out, const PeriodicBspline< ublas::fixed_vector< float_t, 2 > > &curve)
void interpolation_matrix (const Bspline< float_t > &spline, const ublas::vector< float_t > &values, ublas::compressed_matrix< float_t > &matrix)
void interpolation_matrix (const PeriodicBspline< float_t > &spline, const ublas::vector< float_t > &values, ublas::compressed_matrix< float_t > &matrix)
void basis_spline_matrix (const PeriodicBspline< float_t > &spline, const ublas::vector< float_t > &values, ublas::compressed_matrix< float_t > &matrix)
void basis_spline_matrix (const Bspline< float_t > &spline, const ublas::vector< float_t > &values, ublas::compressed_matrix< float_t > &matrix)
void basis_spline (size_t i, Bspline< float_t > &spline)
void basis_spline (size_t i, PeriodicBspline< float_t > &spline)
void mean (const ublas::matrix< float_t > &data, ublas::vector< float_t > &result)
void var (const ublas::matrix< float_t > &data, ublas::vector< float_t > &result)
float_t mean (const ublas::vector< float_t > &data)
float_t var (const ublas::vector< float_t > &data)
Variables
const double PI = 3.1415926
const double SQUARE_ROOT_2 = 1.414213562373095049
const double SQUARE_ROOT_3 = 1.73205080757
Detailed Description
Main library namespace (abbreviated as img).
#include <core/imaging2.hpp> This is the main namespace of imaging2. All objects in the class library belong to this namespace with the only exception of the classes in tla. Instead of imaging also the short version img can be used.
Function Documentation
float_t imaging::compute_intersection_volume (const BoundaryDiscretizer< 2 > & shape_a, const BoundaryDiscretizer< 2 > & shape_b)
Compute the area of intersection of two (2-dimensional) discretized shapes.
References imaging::Box< N >::add_point(), do_intersect(), and imaging::BoundaryDiscretizer< N >::n_points().
template<size_t N> bool imaging::increment_index (const ublas::fixed_vector< size_t, N > & dimensions, size_t fixed_component, ublas::fixed_vector< size_t, N > & index) [inline]
Referenced by compute_divergence_field(), max(), min(), and imaging::MumfordShahEnergy< shape_t >::MumfordShahEnergy().